defaults:
  - data: test
  - model: mlp

optimizer:
  solver_eps_abs: 1e-4
  solver_eps_rel: 1e-4
  solver_verbose: false

training:
  learning_rate: 0.0001
  batch_size: 32
  n_epochs: 100
  random_seed: 42
  algo: sequential
  batches_per_eval: 128
  batches_per_epoch: null
  mesh:
    picard: 1
    batch: 1
  picard:
    window_size: 1
    restart_rule: best
    fill_rule: last
